@startuml "Context Diagram"

title "SPWS - Diagrama de contexto do sistema"

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

skinparam backgroundcolor transparent

Person(ActorUser, "Usuário", "É o ator responsável por realizar as interações com o SPWS. Esse ator pode ser do meio acadêmico, um aluno de programação, um usuário do Scratch ou qualquer interessado em obter informações técnicas referentes aos seus projetos Scratch.")

System(SystemSpws, "Sistema SPWS", "O sistema SPWS (Scratch Projects Web Scraper), constituído de um back-end desenvolvido em Flask/Python e um front-end em React/Javascript. Seu principal papel é prover ao usuário a capacidade de visualizar projetos Scratch de forma mais alto nível no que diz respeito ao seu código-fonte. O sistema utiliza um miniparser feito em Python para esse propósito.")
System_Ext(SystemSupabase, "Supabase Postgres", "É responsável por persistir os dados extraídos da Scratch API e processados pelo back-end do sistema SPWS.")
System_Ext(SystemScratchApi, "Scratch API", "É responsável por consultar informações internas do Scratch como, por exemplo, o pseudocódigo dos projetos em formato JSON e seus metadados.")

Rel(ActorUser, SystemSpws, "Visualiza e interage com as funcionalidades do Scratch Analyzer.", "Web/HTML")
Rel(SystemSpws, SystemSupabase, "Realiza consultas e execução de comandos no banco de dados Postgres.", "PL/SQL over TCP/IP")
Rel(SystemSpws, SystemScratchApi, "Realiza chamadas para consultar projetos, studios do scratch.", "HTTP over TCP/IP")

@enduml
