@startuml "Use Case Diagram"

title "Diagrama de Casos de Uso do SPWS"

skinparam Style strictuml

scale 2048 width
scale 2048 height

actor "Usuário" as USER

usecase "[UC-01] Extrair identificadores e metadados dos projetos do Scratch"         as UC01
usecase "[UC-02] Obter as informações dos blocos utilizados em cada um dos projetos"  as UC02
usecase "[UC-03] Realizar a contagem dos tipos blocos utilizados"                     as UC03
usecase "[UC-04] Baixar projetos que já foram armazenados"                            as UC04
usecase "[UC-05] Realizar pesquisa de um projeto"                                     as UC05
usecase "[UC-06] Exibir dados dos projetos"                                           as UC06
usecase "[UC-07] Realizar pesquisa de projetos por turma"                             as UC07

USER -- UC01
USER -- UC02
USER -- UC03
USER -- UC05
USER -- UC07

UC03 ..> UC02 : <<extend>>
UC05 <.. UC06 : <<extend>>
UC05 <.. UC04 : <<extend>>

@enduml
