@startuml "Container Diagram"

title "SPWS - Diagrama de container do sistema"

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

skinparam backgroundcolor transparent

Person(ActorUser, "Usuário", "É o ator responsável por realizar as interações com o SPWS. Esse ator pode ser do meio acadêmico, um aluno de programação, um usuário do Scratch ou qualquer interessado em obter informações técnicas referentes aos seus projetos Scratch.")

Container_Boundary(SystemSpws, "Sistema SPWS") {
  Container(ContainerWebApp, "Aplicação Web", "Container: React/JavaScript", "Provê aos usuários acesso as funcionalidades a partir do cliente.")
  Container(ContainerServerApi, "API REST", "Container: Flask/Python", "Provê as funcionalidades do SPWS via API JSON/HTTPS.")
  
  Rel(ContainerWebApp, ContainerServerApi, "Faz uma chamada para API", "JSON/HTTPS")
}

System_Ext(SystemSupabase, "Supabase Postgres", "É responsável por persistir os dados extraídos da Scratch API e processados pelo back-end do sistema SPWS.")
System_Ext(SystemScratchApi, "Scratch API", "É responsável por consultar informações internas do Scratch como, por exemplo, o pseudocódigo dos projetos em formato JSON e seus metadados.")

Rel(ActorUser, ContainerWebApp, "Visualiza e interage com as funcionalidades do Scratch Analyzer.", "Web/HTML")
Rel(ContainerServerApi, SystemSupabase, "Realiza consultas e execução de comandos no banco de dados Postgres.", "PL/SQL over TCP/IP")
Rel(ContainerServerApi, SystemScratchApi, "Realiza chamadas para consultar projetos, studios do scratch.", "HTTP over TCP/IP")

@enduml
