@startuml "Component Diagram"

title "Diagrama de Componentes do SPWS"

left to right direction

interface "Link do projeto do Scratch" AS INTERFACE_SCRATCH_PROJECT_LINK

cloud "Internet pública" as CLOUD_01 {

  database "Supabase Database" as COMP_DATABASE {
    component "Postgres Driver" as COMP_DATABASE_DRIVER
  }

  component "Scratch API" as COMP_SCRATCH_API {
    component "Scratch MIT" as COMP_SCRATCH_SERVER
  }

}

cloud "SPWS Infrastructure" as CLOUD_02 {

  component "Scratch Analyzer API" as COMP_OAUTH2_AUTHORIZATION {
    component "Project Flask Resource" as COMP_PROJECT_FLASK_RESOURCE
    component "Project Flask Controller" as COMP_PROJECT_FLASK_CONTROLLER
    component "Project Service" as COMP_PROJECT_SERVICE
    component "Project Utilities" as COMP_PROJECT_UTILITIES

    INTERFACE_SCRATCH_PROJECT_LINK -(0- COMP_PROJECT_FLASK_RESOURCE
    COMP_PROJECT_FLASK_RESOURCE -(0- COMP_PROJECT_FLASK_CONTROLLER
    COMP_PROJECT_FLASK_CONTROLLER -up(0- COMP_PROJECT_SERVICE
    
    COMP_PROJECT_SERVICE -up(0- COMP_DATABASE_DRIVER
    COMP_PROJECT_SERVICE -left(0- COMP_PROJECT_UTILITIES
    COMP_PROJECT_SERVICE -(0 COMP_SCRATCH_SERVER
  }

}

note top of INTERFACE_SCRATCH_PROJECT_LINK
  Esse é o momento onde o usuário 
  faz a requisição para o SPWS e
  fornece a URL do projeto Scratch
  para obter as informações de
  análise do pseudocódigo do projeto.
end note

@enduml
