@startuml "Deployment Diagram"

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

left to right direction

title "Diagrama de Implantação do SPWS"

node "Computador do Usuário" <<device>> as NODE_COMPUTER {
  component "Navegador Google Chrome" <<software>>
}

node "Servidor Web SPWS" <<device>> as NODE_WEBSERVER {
  node "Python >=v3.7.0" <<software>> as NODE_WEBSERVER_RUNTIME {
    artifact "scratch_analyzer_api-1.0" <<software>>
  }
}

database "Servidor de Banco de Dados Supabase" <<device>> as NODE_DATABASE {
  component "Postgres Database Driver" <<software>> as DATABASE_DRIVER
  artifact "Postgres 13.3" <<dbms>> as DATABASE_DBMS
  DATABASE_DRIVER -> DATABASE_DBMS : <b>uses</b>
}

NODE_COMPUTER -up- NODE_WEBSERVER : <<HTTPS>>
NODE_WEBSERVER -down- NODE_DATABASE : <<TCP/IP>>

@enduml
